import Sidebar from "@/components/layouts/Sidebar/Sidebar";
import styles from "./RootLayout.module.css";
import "../app/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={styles.rootLayout}>
        <div>
          <Sidebar />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
