import Sidebar from "@/components/layouts/Sidebar/Sidebar";
import "@/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <div className="sidebar_container">
          <Sidebar />
        </div>
        <main className="mainContent">{children}</main>
      </body>
    </html>
  );
}
