import Sidebar from "@/components/layouts/Sidebar/Sidebar";
import styles from "./RootLayout.module.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={styles.main}>
      <Sidebar />
      <body>{children}</body>
    </html>
  );
}
